### ISSUE TITLE
Adding support for SeeTouchHybridKeypad

### ISSUE THREAD

**Issue by danaues** [danaues/lutron_caseta#3]
Device trigger is failing for the SeeTouchHybridKeypad Keypad.  
Support needs to be added to device_trigger.py

**Comment by danaues** [comment]
@swamplynx 
Is this a SeeTouchHybridKeypad?  We probably have to add support for it in the HA integration.  

Please check your logs to see there are any errors related to retrieving triggers when you edit or create a new automation using this device. 

Thanks

**Comment by swamplynx** [comment]
Yes. It is a seeTouchHybrid. I believe below is the error that is generated when I add it as a device trigger.

`2022-10-19 12:17:30.954 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'function object' has no attribute 'update' when rendering '{% if input_min_update_age == 0 %}
{{ states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed) | map(attribute='entity_id') | list }}
{% else %}
{% set output = namespace(sensors=[]) %}
{% for state in (states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed)) %}
{% if as_timestamp(state.last_changed) <= as_timestamp(now()-timedelta(days=input_min_update_age)) %}
{% set output.sensors = output.sensors + [state.entity_id] %}
{% endif %}
{% endfor %}
{{ output.sensors | list }}
{% endif %}'`

I also see the below related to the seeTouchHybrid, but not sure which action the time stamp aligns with:
`2022-10-19 11:18:38.499 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547018070464] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 378, in ws_event_stream
last_event_time = await _async_send_historical_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 105, in _async_send_historical_events
message, last_event_time = await _async_get_ws_stream_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 170, in _async_get_ws_stream_events
return await get_instance(hass).async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 201, in _ws_stream_get_events
events = event_processor.get_events(start_day, end_day)
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 164, in get_events
return self.humanify(yield_rows(session.execute(stmt)))
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 170, in humanify
return list(
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 231, in _humanify
data = describe_event(event_cache.get(row))
File "/config/custom_components/lutron_caseta/logbook.py", line 34, in async_describe_button_event
button_map = LEAP_TO_DEVICE_TYPE_SUBTYPE_MAP[device_type]
KeyError: 'SeeTouchHybridKeypad'
2022-10-19 11:19:35.243 ERROR (DbWorker_0) [homeassistant.components.recorder.util] Error executing query: 'SeeTouchHybridKeypad'`

**Comment by danaues** [comment]
KeyError: 'SeeTouchHybridKeypad'

This is what's causing the device trigger to not function.  I have to add all the different SeeTouchHybridKeypad variants into the device_triggers.py file.

Working on it.  I can use your diagnostic config from the other issue to flesh out most of it.

**Comment by danaues** [comment]
If you want to test it out, overwrite the device_triggers.py in your config/custom_components/lutron_caseta/ folder with this file:

https://github.com/danaues/core/blob/SeeTouchHybridKeypad/homeassistant/components/lutron_caseta/device_trigger.py

I've added support for the RRD-HN1RLD and the RRD-HN6BRL that you have in your config

The commit is here if you want to check it out
https://github.com/danaues/core/commit/807f9232de8fc2098d5647f194a5b0508c509312

**Comment by swamplynx** [comment]
Something is still causing the integration to crash. I loaded the new module and restarted core. I have a very simple automation that looks for a keypad button press via device trigger and fires a notification. When I press the button nothing happens, and there is no automation trace. I can still see the event under developer tools. Then if I reload the integration the notification comes through. Logs...

`2022-10-19 13:20:12.234 ERROR (DbWorker_0) [homeassistant.components.recorder.util] Error executing query: 'SeeTouchHybridKeypad'
2022-10-19 13:20:12.244 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547622345728] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 378, in ws_event_stream
last_event_time = await _async_send_historical_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 105, in _async_send_historical_events
message, last_event_time = await _async_get_ws_stream_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 170, in _async_get_ws_stream_events
return await get_instance(hass).async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 201, in _ws_stream_get_events
events = event_processor.get_events(start_day, end_day)
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 164, in get_events
return self.humanify(yield_rows(session.execute(stmt)))
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 170, in humanify
return list(
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 231, in _humanify
data = describe_event(event_cache.get(row))
File "/config/custom_components/lutron_caseta/logbook.py", line 34, in async_describe_button_event
button_map = LEAP_TO_DEVICE_TYPE_SUBTYPE_MAP[device_type]
KeyError: 'SeeTouchHybridKeypad'
2022-10-19 13:20:44.223 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'function object' has no attribute 'update' when rendering '{% if input_min_update_age == 0 %}
{{ states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed) | map(attribute='entity_id') | list }}
{% else %}
{% set output = namespace(sensors=[]) %}
{% for state in (states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed)) %}
{% if as_timestamp(state.last_changed) <= as_timestamp(now()-timedelta(days=input_min_update_age)) %}
{% set output.sensors = output.sensors + [state.entity_id] %}
{% endif %}
{% endfor %}
{{ output.sensors | list }}
{% endif %}'
2022-10-19 13:21:09.443 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'function object' has no attribute 'update' when rendering '{% if input_min_update_age == 0 %}
{{ states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed) | map(attribute='entity_id') | list }}
{% else %}
{% set output = namespace(sensors=[]) %}
{% for state in (states.update | selectattr('state','eq','on') | rejectattr('entity_id', 'in', input_update_exclusions_processed)) %}
{% if as_timestamp(state.last_changed) <= as_timestamp(now()-timedelta(days=input_min_update_age)) %}
{% set output.sensors = output.sensors + [state.entity_id] %}
{% endif %}
{% endfor %}
{{ output.sensors | list }}
{% endif %}'`

**Comment by danaues** [comment]
Ok, I had to revise how DeviceType model identifiers are listed.  The Sunnata have a "-XX" at the end of the model, and the SeeTouch does not.  (RRST-W2B-XX for Sunnata, RRD-HN1RLD for SeeTough)

Can you try this again when you have time:
https://github.com/danaues/core/blob/SeeTouchHybridKeypad/homeassistant/components/lutron_caseta/device_trigger.py

Thanks

**Comment by swamplynx** [comment]
That seemed to screw up the parsing of the button name in the automation device picker, but the entities still look correct.
![Capture2](https://user-images.githubusercontent.com/13987471/196811046-4eba5c1b-7f7a-4718-a218-3514fa987dae.JPG)

`Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 378, in ws_event_stream
last_event_time = await _async_send_historical_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 105, in _async_send_historical_events
message, last_event_time = await _async_get_ws_stream_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 170, in _async_get_ws_stream_events
return await get_instance(hass).async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 201, in _ws_stream_get_events
events = event_processor.get_events(start_day, end_day)
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 164, in get_events
return self.humanify(yield_rows(session.execute(stmt)))
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 170, in humanify
return list(
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 231, in _humanify
data = describe_event(event_cache.get(row))
File "/config/custom_components/lutron_caseta/logbook.py", line 34, in async_describe_button_event
button_map = LEAP_TO_DEVICE_TYPE_SUBTYPE_MAP[device_type]
KeyError: 'SeeTouchHybridKeypad'
2022-10-19 17:41:53.209 ERROR (DbWorker_0) [homeassistant.components.recorder.util] Error executing query: 'SeeTouchHybridKeypad'
2022-10-19 17:41:53.212 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547457618496] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
await func(hass, connection, msg)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 378, in ws_event_stream
last_event_time = await _async_send_historical_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 105, in _async_send_historical_events
message, last_event_time = await _async_get_ws_stream_events(
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 170, in _async_get_ws_stream_events
return await get_instance(hass).async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/src/homeassistant/homeassistant/components/logbook/websocket_api.py", line 201, in _ws_stream_get_events
events = event_processor.get_events(start_day, end_day)
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 164, in get_events
return self.humanify(yield_rows(session.execute(stmt)))
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 170, in humanify
return list(
File "/usr/src/homeassistant/homeassistant/components/logbook/processor.py", line 231, in _humanify
data = describe_event(event_cache.get(row))
File "/config/custom_components/lutron_caseta/logbook.py", line 34, in async_describe_button_event
button_map = LEAP_TO_DEVICE_TYPE_SUBTYPE_MAP[device_type]
KeyError: 'SeeTouchHybridKeypad'`

**Comment by danaues** [comment]
Yes, that's ok.  I can add the Group 1 Button 3 wording, it's part of the language translation that happens.
Unfortunately, we can't use our customized button names (from the engravings) for the device triggers.  It has to do with the way HA loads them up.  They will all show as "Button 1" or "Group 1 Button 1" for now.

This won't affect the entity naming.

Do the triggers work now, ignoring the naming in the dropdown?

**Comment by swamplynx** [comment]
Yep! Device triggers are working now! I believe my "[homeassistant.helpers.template] Template variable warning: 'function object' has no attribute 'update' when rendering '" error is related to HA not liking my event based trigger for some reason, even though it also works.

**Comment by danaues** [comment]
@swamplynx the actual Fix in Home Assistant looks a little different than the fix you were testing.
I'm dynamically generating the triggers, so we don't have to code each type of keypad.
As a bonus, your real (engraved) button names will show up in the dropdown lists.

Here is the PR:
https://github.com/home-assistant/core/pull/80797

**Comment by swamplynx** [comment]
Awesome! Can I just clone your dynamic_triggers repo as the latest version of the integration? Also going to change the manifest to req the 0.17.1 pylutron_Caseta code, since that was just published. 

Do you think the changes will cause any duplication of existing devices / entities? Just trying to estimate the amount of time I need to block off for the update.

**Comment by danaues** [comment]
You can clone my dynamic_triggers repo.  You will still have the screwy home name in the areas. 
0.17.1 is 1/2 of the fix for that.  I need to post another PR to HA after this device trigger one is complete to finish that fix.

Should not duplicate or change any entities.  You will probably get an error on your device trigger automations, but you just have to open them up, and reselect the correct button from the trigger dropdown.

**Comment by danaues** [comment]
Give me a bit of time (couple hours) and I'll post something for you that will have all the fixes.  I'm just working through a small issue with moving from the old trigger names to the new ones.  Want to make sure it's easy to update automations.

**Comment by swamplynx** [comment]
Awesome. No rush at all.

**Comment by danaues** [comment]
Everything has been merged into [core/dev](https://github.com/home-assistant/core) now.  
Full trigger support, area name fixes, and the bump to pylutorn-caseta 0.17.1, also zeroconf discovery.

**Comment by swamplynx** [comment]
@danaues , everything is working great in the latest dev version. Thank you again for all your tremendous work in getting this updated for RA3.
